Processing Data in models
edahigure/blog-app pull request #2
Opened 2023-05-17 16:25 UTC by edahigure

### Project requirements

### Create models
-  Create model classes for all entities as shown in the [ERD diagram](../images/blog_app_erd_v1_1.png).
-  Set up associations between models.
    - Remember that `author_id` column in `posts` table should be the foreign_key for the `users` table.

### Use models to insert data
- Familiarize yourself with ['rails c' command](https://guides.rubyonrails.org/command_line.html#bin-rails-console).
- Open rails console for your project.
- Create at least one user by running the following code:
    ```ruby
       first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
       second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
    ```
- Create at least 4 posts written by one of the users you created by running the following code:
    ```ruby
       first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
    ```
- Create at least 6 posts comments for one of the posts you created by running the following code:
    ```ruby
       Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
    ```
- Use other [CRUD methods](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/lessons/active_record_crud.md) to find, update and delete entities.

### Create custom methods
Your models should include some additional methods.
-  Users
    - A method that returns the 3 most recent posts for a given user.
-  Posts
    - A method that updates the posts counter for a user.
    - A method which returns the 5 most recent comments for a given post.
-  Comments
    - A method that updates the comments counter for a post.
-  Likes
    - A method that updates the likes counter for a post.
- Go to `rails c` and check if your methods are working.

2023-05-17 16:37 UTC, Ismailco reviewed
Hi @edahigure, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has some linter errors and doesn't have the `.github/linters` folder that includes tests for the linters checks on github

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-17 19:01 UTC, Whoistolu requested changes
Hi @edahigure 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 19:01 UTC, Whoistolu commented on app/models/user.rb
> +  end
- [ ] [REQUIRED] Let's note that the User table is connected to the `Post`, `Comment`, and `Like` tables through a foreign_key: `author_id`. Kindly implement this because you have forgotten to do that.  Foreign keys here establish relationships between the `User`, `Comment`, `Like`, and `Post` tables, allowing for easy navigation and querying across related data. 

- [ ] [OPTIONAL] In order to have a more standard and professionally well-written code, I will suggest you leave/create a space between the `has_many` relationship and the `recent_posts` method.

2023-05-17 19:01 UTC, Whoistolu commented on app/models/post.rb
> +  def update_posts_counter
- [ ] [OPTIONAL] In order to have a more standard and professionally well-written code, I will suggest you leave/create a space between the `has_many` relationship and the `update_posts_counter` method.

2023-05-17 19:01 UTC, Whoistolu commented on app/models/like.rb
> +  def update_likes_counter
- [ ] [OPTIONAL] In order to have a more standard and professionally well-written code, I will suggest you leave/create a space between the `belong_to` relationship and the `update_likes_counter` method.

2023-05-18 21:11 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle: :1st_place_medal: :100:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

### Hey @edahigure 👋

Great work on implementing the requested changes. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following Requirements
✔️ Added Relationships as expected 👍 🔥 🥇

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 21:11 UTC, HAMMAS-SALEEM commented on app/models/post.rb
> +
**[OPTIONAL]**

- [ ] Kindly make this method private because this method should not be accessed by the users directly 👍 😊

2023-05-18 21:11 UTC, HAMMAS-SALEEM commented on app/models/comment.rb
> +  end
**[OPTIONAL]**

- [ ] Kindly make this method private because this method should not be accessed by the users directly 👍 😊

2023-05-18 21:11 UTC, HAMMAS-SALEEM commented on app/models/like.rb
> +  end
**[OPTIONAL]**

- [ ] Kindly make this method private because this method should not be accessed by the users directly 👍 😊

2023-05-19 15:34 UTC, merged